/**
 * Math Tool Renderer
 *
 * Renders visual math tools (diagrams) generated by AI for practice problems.
 * Reuses existing Socratic mode visualizers.
 */

import React from 'react';

// Import all existing Socratic visualizers
import RightTriangleVisualizer from '../math-tools/RightTriangleVisualizer';
import ElevationDepressionVisualizer from '../math-tools/ElevationDepressionVisualizer';
import GeneralTriangleVisualizer from '../math-tools/GeneralTriangleVisualizer';
import CuboidVisualizer from '../math-tools/CuboidVisualizer';
import PyramidVisualizer from '../math-tools/PyramidVisualizer';
import BearingsVisualizer from '../math-tools/BearingsVisualizer';

interface MathToolRendererProps {
  toolName: string;
  parameters: Record<string, any>;
  caption?: string;
}

export const MathToolRenderer: React.FC<MathToolRendererProps> = ({
  toolName,
  parameters,
  caption
}) => {
  // Render the appropriate visualizer based on toolName
  const renderTool = () => {
    switch (toolName) {
      case 'rightTriangle':
        return <RightTriangleVisualizer {...parameters} />;

      case 'elevationDepression':
        return <ElevationDepressionVisualizer {...parameters} />;

      case 'generalTriangle':
        return <GeneralTriangleVisualizer {...parameters} />;

      case 'cuboid':
        return <CuboidVisualizer {...parameters} />;

      case 'pyramid':
        return <PyramidVisualizer {...parameters} />;

      case 'bearings':
        return <BearingsVisualizer {...parameters} />;

      default:
        console.warn(`Unknown tool name: ${toolName}`);
        return (
          <div className="p-4 bg-yellow-50 border border-yellow-300 rounded text-yellow-800">
            Unknown visualization: {toolName}
          </div>
        );
    }
  };

  return (
    <div className="my-4 p-4 bg-white rounded-lg border-2 border-gray-200">
      {/* Render the visualization */}
      <div className="flex justify-center">
        {renderTool()}
      </div>

      {/* Optional caption */}
      {caption && (
        <div className="mt-3 text-center text-sm text-gray-600 italic">
          {caption}
        </div>
      )}
    </div>
  );
};
